# Copyright IBM Corp, All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

FROM node:8.10 as build_js
COPY src/static /var/www/
RUN cd /var/www/dashboard && npm install && npm run build:dev

FROM hyperledger/cello-baseimage:latest

COPY --from=build_js /var/www/dist /app/static/dist
#COPY --from=build_js /tmp/cello/src/celery.conf /etc/supervisor/conf.d/
COPY src/celery.conf /etc/supervisor/conf.d/
CMD /etc/init.d/supervisor start && if [ "$DEBUG" = "True" ]; then python dashboard.py ; else gunicorn -w 1 --worker-class eventlet -b 0.0.0.0:8080 dashboard:app ;fi